### ISSUE TITLE
Handling utf8

### ISSUE THREAD

**Issue by athoune** [0x09AL/raven#2]
```
Traceback (most recent call last):
  File "raven.py", line 79, in <module>
    RequesterObject.doLogin(linkedinUsername,linkedinPassword)
  File "/private/tmp/raven/modules/requester.py", line 31, in doLogin
    if(str(self.driver.title).startswith("Sign In")):
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe0' in position 15: ordinal not in range(128)
```

Yes, python strings with utf8 are painful.

**Comment by 0x09AL** [comment]
This issue has been fixed by encoding the title only in ascii.
