### ISSUE TITLE
OSX port

### ISSUE THREAD

**Issue by Green-Wolf** [0x09AL/raven#6]
Hey nice tool,

Any chance of getting it ported so it works on osx? 

I've installed geckodrive to /usr/local/bin instead of /usr/bin and installed with sudo but i get the following error: 
`Traceback (most recent call last):
  File "raven.py", line 56, in <module>
    RequesterObject = requester.Requester()
  File "/path/raven/modules/requester.py", line 22, in __init__
    self.driver = webdriver.Firefox()
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 144, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/common/service.py", line 74, in start
    stdout=self.log_file, stderr=self.log_file)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error`

**Edit: Also not working on Kali:**
root@kali:/Desktop/raven# python raven.py -c 'company' -s US -d company.com
Traceback (most recent call last):
  File "raven.py", line 2, in <module>
    from modules import requester
  File "/root/Desktop/raven/modules/requester.py", line 1, in <module>
    from selenium import webdriver
ImportError: No module named selenium
root@kali:~/Desktop/raven# pip install selenium

Collecting selenium
  Could not find a version that satisfies the requirement selenium (from versions: )
No matching distribution found for selenium

**Comment by 0x09AL** [comment]
Hi,
Thanks for opening the issue. I think this tool should work on macos without a problem you just need to install selenium. You can find a lot of references online.

**Comment by Green-Wolf** [comment]
Just for anyone who comes across this to get it working on OSX:
pip install selenium
cp geckodriver /usr/local/bin
Update firefox to latest version
